# Generated by Django 3.2 on 2021-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Синий'), ('brown', 'Коричневый')], default='brown', max_length=64),
        ),
    ]
