# Generated by Django 3.2 on 2021-05-04 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_actor_eye_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 4, 17, 51, 35, 318458)),
        ),
        migrations.AddField(
            model_name='actor',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actor',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Синий'), ('brown', 'Коричневый'), ('cyan', 'Голубые')], default='brown', max_length=64),
        ),
    ]
