# Generated by Django 3.2 on 2021-05-04 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_actor_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='body_type',
            field=models.CharField(choices=[('normal', 'Обычное'), ('thin', 'Худощавое'), ('athletic', 'Спортивное'), ('fat', 'Полное')], default='thin', max_length=64),
        ),
        migrations.AddField(
            model_name='actor',
            name='hair_color',
            field=models.CharField(choices=[('brunette', 'Брюнет'), ('red', 'Рыжий'), ('blond', 'Блондин'), ('brown', 'Шатен'), ('gray', 'Седой')], default='brunette', max_length=64),
        ),
        migrations.AddField(
            model_name='actor',
            name='nation',
            field=models.CharField(default='nonation', max_length=64),
        ),
        migrations.AddField(
            model_name='actor',
            name='race',
            field=models.CharField(choices=[('mongoloid', 'Монголоидная'), ('caucasian', 'Европеоидная'), ('negroid', 'Негроидная')], default='mongoloid', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 4, 19, 3, 26, 631245)),
        ),
    ]
