# Generated by Django 3.2 on 2021-05-05 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210504_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 10, 26, 11, 999233)),
        ),
        migrations.AlterField(
            model_name='actor',
            name='body_type',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('normal', 'Обычное'), ('thin', 'Худощавое'), ('athletic', 'Спортивное'), ('fat', 'Полное')], default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='education',
            field=models.CharField(default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='eye_color',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('blue', 'Синий'), ('brown', 'Коричневый'), ('cyan', 'Голубые')], default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='hair_color',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('brunette', 'Брюнет'), ('red', 'Рыжий'), ('blond', 'Блондин'), ('brown', 'Шатен'), ('gray', 'Седой')], default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='location',
            field=models.CharField(default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name1',
            field=models.CharField(default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name2',
            field=models.CharField(default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name3',
            field=models.CharField(default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nation',
            field=models.CharField(default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='race',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('mongoloid', 'Монголоидная'), ('caucasian', 'Европеоидная'), ('negroid', 'Негроидная')], default='mongoloid', max_length=64),
        ),
    ]
