# Generated by Django 3.2 on 2021-05-05 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210505_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 11, 58, 38, 757659)),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name1',
            field=models.CharField(default='NONE', max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name2',
            field=models.CharField(default='NONE', max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name3',
            field=models.CharField(default='NONE', max_length=64, verbose_name='Отчество'),
        ),
    ]
