# Generated by Django 3.2 on 2021-05-05 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210505_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='sex',
            field=models.CharField(default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 18, 47, 30, 603742)),
        ),
    ]
