# Generated by Django 3.2 on 2021-05-05 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210505_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 18, 49, 4, 760402)),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('male', 'Мужской'), ('female', 'Женский')], default='NONE', max_length=64),
        ),
    ]
