# Generated by Django 3.2 on 2021-05-06 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210506_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 15, 19, 12, 382546), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='body_type',
            field=models.CharField(choices=[('', 'Not selected'), ('normal', 'Normal'), ('thin', 'Thin'), ('athletic', 'Athletic'), ('fat', 'Fat')], default='', max_length=64, verbose_name='Body type'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='education',
            field=models.CharField(default='', max_length=64, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='eye_color',
            field=models.CharField(choices=[('', 'Not selected'), ('blue', 'Blue'), ('brown', 'Brown'), ('cyan', 'Cyan')], default='', max_length=64, verbose_name='Eye color'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='hair_color',
            field=models.CharField(choices=[('', 'Not selected'), ('brunette', 'Brunette'), ('red', 'Red'), ('blond', 'Blond'), ('brown', 'Brown'), ('gray', 'Gray')], default='', max_length=64, verbose_name='Hair color'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='location',
            field=models.CharField(default='', max_length=64, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nation',
            field=models.CharField(default='', max_length=64, verbose_name='Nation'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='race',
            field=models.CharField(choices=[('', 'Not selected'), ('mongoloid', 'Mongoloid'), ('caucasian', 'Caucasian'), ('negroid', 'Negroid')], default='mongoloid', max_length=64, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[('', 'Not selected'), ('male', 'Male'), ('female', 'Female')], default='', max_length=64, verbose_name='Sex'),
        ),
    ]
