# Generated by Django 3.2 on 2021-05-06 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210506_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 15, 32, 41, 531438), verbose_name='Birthday'),
        ),
    ]
