# Generated by Django 3.2 on 2021-05-06 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210506_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 17, 12, 14, 178207), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(default='NONAME', max_length=64, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(default='NONAME', max_length=64, verbose_name='Full name'),
        ),
    ]
