# Generated by Django 3.2 on 2021-05-06 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210506_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(default='', max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 20, 54, 45, 423681), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='position',
            field=models.CharField(default='', max_length=64, verbose_name='Position'),
        ),
    ]
