# Generated by Django 3.2 on 2021-05-06 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210506_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 21, 1, 55, 826456), verbose_name='Birthday'),
        ),
    ]
