# Generated by Django 3.2 on 2021-05-06 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_actor_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Birthday'),
        ),
    ]
