# Generated by Django 3.2 on 2021-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210506_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='Title'),
        ),
    ]
