# Generated by Django 3.2 on 2021-05-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_role_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestactortorole',
            name='status',
            field=models.CharField(default='Not considered', max_length=64),
        ),
        migrations.AddField(
            model_name='requestroletoactor',
            name='status',
            field=models.CharField(default='Not considered', max_length=64),
        ),
    ]
